--- # Gather EC2 Facts from my remote instance
- hosts: amazon
  remote_user: ec2-user
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Gather facts abt running instance
    action: ec2_facts
  - name: Display the instance type
    debug: msg='{{ ansible_ec2_instance_type }}'


